---
- name: Node.js uygulaması için PM2'yi global olarak kur
  npm:
    name: pm2
    global: yes

- name: GitHub'dan uygulama kodlarını çek
  git:
    repo: 'https://github.com/aziz-mevlana/hello-world-node.git'
    dest: /var/www/hello-world
    version: main
    force: yes

- name: NPM bağımlılıklarını yükle
  npm:
    path: /var/www/hello-world

- name: Uygulamayi PM2 listesinden sil ve sifirdan baslat
  shell: |
    pm2 delete hello-world || true
    pm2 start server.js --name "hello-world"
  args:
    chdir: /var/www/hello-world
